const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
const ORDER_PAY_RESET = "ORDER_PAY_RESET";

const PAYMENT_INTENT_REQUEST = "PAYMENT_INTENT_REQUEST";
const PAYMENT_INTENT_SUCCESS = "PAYMENT_INTENT_SUCCESS";
const PAYMENT_INTENT_FAIL = "PAYMENT_INTENT_FAIL";
const PAYMENT_INTENT_RESET = "PAYMENT_INTENT_RESET";

export {
    ORDER_CREATE_REQUEST,
    ORDER_CREATE_SUCCESS,
    ORDER_CREATE_FAIL,
    ORDER_DETAILS_REQUEST,
    ORDER_DETAILS_SUCCESS,
    ORDER_DETAILS_FAIL,
    ORDER_PAY_REQUEST,
    ORDER_PAY_SUCCESS,
    ORDER_PAY_FAIL,
    ORDER_PAY_RESET,
    PAYMENT_INTENT_REQUEST,
    PAYMENT_INTENT_SUCCESS,
    PAYMENT_INTENT_FAIL,
    PAYMENT_INTENT_RESET
}